# Generated by scripts/update.sh from the v0.8.13 release of tsvsheet/isnow.go — do not edit by hand.
class Isnow < Formula
  desc "Match instants against isnow date/time patterns"
  homepage "https://tsvsheet.com"
  version "0.8.13"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.13/isnow-0.8.13-darwin-arm64.tar.gz"
      sha256 "99f900fc538ca15fd17bd85eae2c489805bfb0abad9281385a4110470f5ff1e3"
    end
    on_intel do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.13/isnow-0.8.13-darwin-amd64.tar.gz"
      sha256 "9e3384c599d11d27e0fe129319f2a93156a13b832bdbfb3d3f99e9a4cb92388e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.13/isnow-0.8.13-linux-arm64.tar.gz"
      sha256 "bc54d7f10e2208fd858595f569b14b263103ba0bcee2e903a08d9762a4b99f33"
    end
    on_intel do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.13/isnow-0.8.13-linux-amd64.tar.gz"
      sha256 "8a5689aba249f440d17ee05e66778ab49b5891cafb55bcff3ada0ca6da1cf1db"
    end
  end

  def install
    bin.install Dir["isnow-*"].first => "isnow"
    bash_completion.install "completions/isnow.bash" => "isnow" if File.exist?("completions/isnow.bash")
    zsh_completion.install "completions/isnow.zsh" => "_isnow" if File.exist?("completions/isnow.zsh")
    fish_completion.install "completions/isnow.fish" if File.exist?("completions/isnow.fish")
    man1.install "man/isnow.1" if File.exist?("man/isnow.1")
  end

  test do
    system "#{bin}/isnow", "--version"
  end
end
