# Generated by scripts/update.sh from the v0.8.0 release of tsvsheet/isnow.go — do not edit by hand.
class Isnow < Formula
  desc "Match instants against isnow date/time patterns"
  homepage "https://tsvsheet.com"
  version "0.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.0/isnow-0.8.0-darwin-arm64.tar.gz"
      sha256 "a1021a4a446fe979c7b9b1c1f02883512d63d5ec039c980f5633377fc77aa977"
    end
    on_intel do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.0/isnow-0.8.0-darwin-amd64.tar.gz"
      sha256 "7885dd0b1a9bf43a752620c7a77a0cac0000bab6f7232ae532ddf82938f1d64f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.0/isnow-0.8.0-linux-arm64.tar.gz"
      sha256 "8209907c1e1f070aa54cb178341c37b21be635ef028bcec8accc6ee7e1b5e0aa"
    end
    on_intel do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.0/isnow-0.8.0-linux-amd64.tar.gz"
      sha256 "936bf2a443ac691edcf5a1b55a2eb137cfbb3e90771b482ca1b305f7af243a6e"
    end
  end

  def install
    bin.install Dir["isnow-*"].first => "isnow"
    bash_completion.install "completions/isnow.bash" => "isnow" if File.exist?("completions/isnow.bash")
    zsh_completion.install "completions/isnow.zsh" => "_isnow" if File.exist?("completions/isnow.zsh")
    fish_completion.install "completions/isnow.fish" if File.exist?("completions/isnow.fish")
    man1.install "man/isnow.1" if File.exist?("man/isnow.1")
  end

  test do
    system "#{bin}/isnow", "--version"
  end
end
