# Generated by scripts/update.sh from the v0.8.11 release of tsvsheet/isnow.go — do not edit by hand.
class Isnow < Formula
  desc "Match instants against isnow date/time patterns"
  homepage "https://tsvsheet.com"
  version "0.8.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.11/isnow-0.8.11-darwin-arm64.tar.gz"
      sha256 "1d737c731756b3da4cba6e7c620a53c22da5934849852dab9a7dd3b9ad4733a0"
    end
    on_intel do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.11/isnow-0.8.11-darwin-amd64.tar.gz"
      sha256 "5dd7595da2f3ed1cd6aaa8ecb6fbceaaf740dc4642a846b0443f2169fba6808e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.11/isnow-0.8.11-linux-arm64.tar.gz"
      sha256 "4da8831a05a934571d674cc1f8300394cf9d8c2ccce81a390c8fbebdc13bb3a6"
    end
    on_intel do
      url "https://github.com/tsvsheet/isnow.go/releases/download/v0.8.11/isnow-0.8.11-linux-amd64.tar.gz"
      sha256 "5c2a0e033e256cdffb649fddb075e9fdaa46553f4ff3609cd87f01c7fd8802a0"
    end
  end

  def install
    bin.install Dir["isnow-*"].first => "isnow"
    bash_completion.install "completions/isnow.bash" => "isnow" if File.exist?("completions/isnow.bash")
    zsh_completion.install "completions/isnow.zsh" => "_isnow" if File.exist?("completions/isnow.zsh")
    fish_completion.install "completions/isnow.fish" if File.exist?("completions/isnow.fish")
    man1.install "man/isnow.1" if File.exist?("man/isnow.1")
  end

  test do
    system "#{bin}/isnow", "--version"
  end
end
