# Generated by scripts/update.sh from the v0.2.9 release of tsvsheet/tq.go — do not edit by hand.
class Tq < Formula
  desc "Query TSV with a pipeline of relational verbs — the tq query language"
  homepage "https://tsvsheet.com"
  version "0.2.9"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.2.9/tq-0.2.9-darwin-arm64.tar.gz"
      sha256 "db7180e2765774ed73634851c87b21aa29f685773e16cb302d212cf1755507c1"
    end
    on_intel do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.2.9/tq-0.2.9-darwin-amd64.tar.gz"
      sha256 "7db7ddda911398f9cb0546cd64a48b98040057b87a2f2b6e7eda30aafdbbd7da"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.2.9/tq-0.2.9-linux-arm64.tar.gz"
      sha256 "08255757d2bd8f75a8d157d434c3c939445d2b4b2afd2bfe4eb6909548683eb3"
    end
    on_intel do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.2.9/tq-0.2.9-linux-amd64.tar.gz"
      sha256 "aa537d90a48c7b714f7fe250d36c745c676267e612a185fe781cab7c1b75b9a4"
    end
  end

  def install
    bin.install Dir["tq-*"].first => "tq"
    bash_completion.install "completions/tq.bash" => "tq" if File.exist?("completions/tq.bash")
    zsh_completion.install "completions/tq.zsh" => "_tq" if File.exist?("completions/tq.zsh")
    fish_completion.install "completions/tq.fish" if File.exist?("completions/tq.fish")
    man1.install "man/tq.1" if File.exist?("man/tq.1")
  end

  test do
    system "#{bin}/tq", "--version"
  end
end
