# Generated by scripts/update.sh from the v0.3.5 release of tsvsheet/tq.go — do not edit by hand.
class Tq < Formula
  desc "Query TSV with a pipeline of relational verbs — the tq query language"
  homepage "https://tsvsheet.com"
  version "0.3.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.5/tq-0.3.5-darwin-arm64.tar.gz"
      sha256 "ff3d68b391b80587836375e3051a20893f794d1d433f6e208cf9bc4dc494e107"
    end
    on_intel do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.5/tq-0.3.5-darwin-amd64.tar.gz"
      sha256 "0e9b077355afdfd0c01b5d674806a954e5534c6a8ae3c8d1cfc2f4d36e3588d1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.5/tq-0.3.5-linux-arm64.tar.gz"
      sha256 "2acf04e4c933479a7b855d5dcbca0f330b763c45fc451c269a8d6321a2de84dc"
    end
    on_intel do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.5/tq-0.3.5-linux-amd64.tar.gz"
      sha256 "17db162a77f38ec49791bf9e1e902b891a8f29e903cc82a0c4d238f339afb072"
    end
  end

  def install
    bin.install Dir["tq-*"].first => "tq"
    bash_completion.install "completions/tq.bash" => "tq" if File.exist?("completions/tq.bash")
    zsh_completion.install "completions/tq.zsh" => "_tq" if File.exist?("completions/tq.zsh")
    fish_completion.install "completions/tq.fish" if File.exist?("completions/tq.fish")
    man1.install "man/tq.1" if File.exist?("man/tq.1")
  end

  test do
    system "#{bin}/tq", "--version"
  end
end
