# Generated by scripts/update.sh from the v0.3.4 release of tsvsheet/tq.go — do not edit by hand.
class Tq < Formula
  desc "Query TSV with a pipeline of relational verbs — the tq query language"
  homepage "https://tsvsheet.com"
  version "0.3.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.4/tq-0.3.4-darwin-arm64.tar.gz"
      sha256 "81cb333a7af2e13a048100db84a37271f02a245b22f83860eca0609c9b597670"
    end
    on_intel do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.4/tq-0.3.4-darwin-amd64.tar.gz"
      sha256 "5298442e608152b2fd73daec2908e446e28b612cb9fad901e2815565f6401f4f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.4/tq-0.3.4-linux-arm64.tar.gz"
      sha256 "677b3a44593b27a1a7ade8f9561d230c40806ba8ab435559b613cb349d4842a7"
    end
    on_intel do
      url "https://github.com/tsvsheet/tq.go/releases/download/v0.3.4/tq-0.3.4-linux-amd64.tar.gz"
      sha256 "78e70f4e9b937fdecf7ba7aede897e23f10603991a122d34b29b41379271b941"
    end
  end

  def install
    bin.install Dir["tq-*"].first => "tq"
    bash_completion.install "completions/tq.bash" => "tq" if File.exist?("completions/tq.bash")
    zsh_completion.install "completions/tq.zsh" => "_tq" if File.exist?("completions/tq.zsh")
    fish_completion.install "completions/tq.fish" if File.exist?("completions/tq.fish")
    man1.install "man/tq.1" if File.exist?("man/tq.1")
  end

  test do
    system "#{bin}/tq", "--version"
  end
end
