# Generated by scripts/update.sh from the v0.18.1 release of tsvsheet/tsvsheet.go — do not edit by hand.
class Tsv < Formula
  desc "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
  homepage "https://tsvsheet.com"
  version "0.18.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.18.1/tsv-0.18.1-darwin-arm64.tar.gz"
      sha256 "dc9bf6f9fadb0e3bfad16a4264c72852cb24d000fb7162e8cc3d1a0031b6815b"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.18.1/tsv-0.18.1-darwin-amd64.tar.gz"
      sha256 "05fe2d235a20a888b05c1ac9df9479eb0901b531fb2723afa356fb5b22426c07"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.18.1/tsv-0.18.1-linux-arm64.tar.gz"
      sha256 "7e3558ed08057d75b5b461bff746551aa9071ea2c5cf0e36423b39eba16b9e56"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.18.1/tsv-0.18.1-linux-amd64.tar.gz"
      sha256 "8f7d39a86f6189f5a518cb85dc4dbcc9a7ec6b93b7797fc7a63ffc3c21645f0d"
    end
  end

  def install
    bin.install Dir["tsv-*"].first => "tsv"
    bash_completion.install "completions/tsv.bash" => "tsv" if File.exist?("completions/tsv.bash")
    zsh_completion.install "completions/tsv.zsh" => "_tsv" if File.exist?("completions/tsv.zsh")
    fish_completion.install "completions/tsv.fish" if File.exist?("completions/tsv.fish")
    man1.install "man/tsv.1" if File.exist?("man/tsv.1")
  end

  test do
    system "#{bin}/tsv", "--version"
  end
end
