# Generated by scripts/update.sh from the v0.14.0 release of tsvsheet/tsvsheet.go — do not edit by hand.
class Tsv < Formula
  desc "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
  homepage "https://tsvsheet.com"
  version "0.14.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.14.0/tsv-0.14.0-darwin-arm64.tar.gz"
      sha256 "ddc3e3de317e983f6b3106dfe6f70db379417780e9f8e4791d0f21ebf465d89a"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.14.0/tsv-0.14.0-darwin-amd64.tar.gz"
      sha256 "c537ef4a695b72003aafef33d013a77a4268a8360c2b284b34455c99f0833a75"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.14.0/tsv-0.14.0-linux-arm64.tar.gz"
      sha256 "60dd4009c1b0e58878b3287213b46f8ed4d2c5823c07019a6fb62d18875d76e3"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.14.0/tsv-0.14.0-linux-amd64.tar.gz"
      sha256 "846b843ffe7b9cd7d6bcaf92888da15d762ae0c9abd7320dcc63325f437c035c"
    end
  end

  def install
    bin.install Dir["tsv-*"].first => "tsv"
    bash_completion.install "completions/tsv.bash" => "tsv" if File.exist?("completions/tsv.bash")
    zsh_completion.install "completions/tsv.zsh" => "_tsv" if File.exist?("completions/tsv.zsh")
    fish_completion.install "completions/tsv.fish" if File.exist?("completions/tsv.fish")
    man1.install "man/tsv.1" if File.exist?("man/tsv.1")
  end

  test do
    system "#{bin}/tsv", "--version"
  end
end
