# Generated by scripts/update.sh from the v0.5.0 release of tsvsheet/tsvsheet.go — do not edit by hand.
class Tsv < Formula
  desc "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
  homepage "https://tsvsheet.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.5.0/tsv-0.5.0-darwin-arm64.tar.gz"
      sha256 "f96915dc1c3b10619c996e25d61e80aae4dbf03992f28360d786ca5bb72b6755"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.5.0/tsv-0.5.0-darwin-amd64.tar.gz"
      sha256 "7a10b7b7c4d1f8b890141efb7eb9d030d74d710fa4b96187c20929540e90256d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.5.0/tsv-0.5.0-linux-arm64.tar.gz"
      sha256 "04d14f010832cbcefa69338c49e46a9cd05c8bb4ec2e873a3c9ec60f2af0dfb4"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.5.0/tsv-0.5.0-linux-amd64.tar.gz"
      sha256 "637f4f71a4e246912c4f64b6e1ed2ebda2d76f07074ededd0c781db8f74ec615"
    end
  end

  def install
    bin.install Dir["tsv-*"].first => "tsv"
    bash_completion.install "completions/tsv.bash" => "tsv" if File.exist?("completions/tsv.bash")
    zsh_completion.install "completions/tsv.zsh" => "_tsv" if File.exist?("completions/tsv.zsh")
    fish_completion.install "completions/tsv.fish" if File.exist?("completions/tsv.fish")
    man1.install "man/tsv.1" if File.exist?("man/tsv.1")
  end

  test do
    system "#{bin}/tsv", "--version"
  end
end
