# Generated by scripts/update.sh from the v0.1.1 release of tsvsheet/tsvsheet.go — do not edit by hand.
class Tsvsheet < Formula
  desc "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
  homepage "https://tsvsheet.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.1/tsvsheet-0.1.1-darwin-arm64.tar.gz"
      sha256 "0c3c3d57373f4a3be5c3d71b2ef89f8d4d7c98717d322a737099c2d402c024d0"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.1/tsvsheet-0.1.1-darwin-amd64.tar.gz"
      sha256 "81648a72aa06506999fa3b5362a19a3732f9a35822ef695b8084058f387d4366"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.1/tsvsheet-0.1.1-linux-arm64.tar.gz"
      sha256 "e360c10d314258de177cd2802f4c945636580d3e99858212711e504d7df479c0"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.1/tsvsheet-0.1.1-linux-amd64.tar.gz"
      sha256 "05f84eceab1df9fc3ead34de4e17cc70da17e363b531459bb5b520ea37674c69"
    end
  end

  def install
    bin.install Dir["tsvsheet-*"].first => "tsvsheet"
  end

  test do
    system "#{bin}/tsvsheet", "--version"
  end
end
