# Generated by scripts/update.sh from the v0.1.3 release of tsvsheet/tsvsheet.go — do not edit by hand.
class Tsvsheet < Formula
  desc "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
  homepage "https://tsvsheet.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.3/tsvsheet-0.1.3-darwin-arm64.tar.gz"
      sha256 "2dd698b43e2386c2146734af848f4dd16b2749b2ed446296e0a8583d75f06de5"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.3/tsvsheet-0.1.3-darwin-amd64.tar.gz"
      sha256 "858b97890fc250768834cb2dd7eb60e0443dc25acc007f7c5c74ea67b22fd8b9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.3/tsvsheet-0.1.3-linux-arm64.tar.gz"
      sha256 "5b0f55ad5bfc5d95e52db2f5f2e8c273e2673ff166f89aa49abc83ad0d50e71a"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.3/tsvsheet-0.1.3-linux-amd64.tar.gz"
      sha256 "4aa1a4e38d0e12ac6a53dbe8a5d741f6c9bca7c49eac89bc5c5af968d03c4c5e"
    end
  end

  def install
    bin.install Dir["tsvsheet-*"].first => "tsvsheet"
  end

  test do
    system "#{bin}/tsvsheet", "--version"
  end
end
