# Generated by scripts/update.sh from the v0.1.0 release of tsvsheet/tsvsheet.go — do not edit by hand.
class Tsvsheet < Formula
  desc "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
  homepage "https://tsvsheet.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.0/tsvsheet-0.1.0-darwin-arm64.tar.gz"
      sha256 "5f1a71aea50021c94aa822f4d7a4b4e92d8c771ed3e5c1d47ff0dcc18ca1f074"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.0/tsvsheet-0.1.0-darwin-amd64.tar.gz"
      sha256 "634f5886e77d2362490512be1eeb5e580af011f473136f319d5763970caed24f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.0/tsvsheet-0.1.0-linux-arm64.tar.gz"
      sha256 "76a1ea3a71ba3c02817a3c853db62d98dfe56901b4f67b8735aa9738907af821"
    end
    on_intel do
      url "https://github.com/tsvsheet/tsvsheet.go/releases/download/v0.1.0/tsvsheet-0.1.0-linux-amd64.tar.gz"
      sha256 "9ae5f34a1319b11bccd9f70054ee472c9ce85f3ccf0a560234ce16aa6eea36ba"
    end
  end

  def install
    bin.install Dir["tsvsheet-*"].first => "tsvsheet"
  end

  test do
    system "#{bin}/tsvsheet", "--version"
  end
end
