#!/usr/bin/env bash
# Regenerate Formula/*.rb from the latest GitHub releases of the upstream CLI
# repos. Idempotent: run any time; the workflow commits only when output changes.
set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "${0}")/.."

# sha256 of one named asset from a checksums.txt body; fails loudly when absent.
asset_sha() {
  local sums="${1}" file="${2}" sha
  sha="$(printf '%s\n' "${sums}" | awk -v f="${file}" '$2 == f { print $1 }')"
  if [ -z "${sha}" ]; then
    echo "missing checksum for ${file}" >&2
    return 1
  fi
  printf '%s' "${sha}"
}

formula() {
  local name="${1}" repo="${2}" class="${3}" desc="${4}"
  local tag version base sums
  tag="$(gh api "repos/tsvsheet/${repo}/releases/latest" --jq .tag_name)"
  version="${tag#v}"
  base="https://github.com/tsvsheet/${repo}/releases/download/${tag}"
  sums="$(curl -fsSL "${base}/checksums.txt")"

  local sha_darwin_arm sha_darwin_amd sha_linux_arm sha_linux_amd
  sha_darwin_arm="$(asset_sha "${sums}" "${name}-${version}-darwin-arm64.tar.gz")"
  sha_darwin_amd="$(asset_sha "${sums}" "${name}-${version}-darwin-amd64.tar.gz")"
  sha_linux_arm="$(asset_sha "${sums}" "${name}-${version}-linux-arm64.tar.gz")"
  sha_linux_amd="$(asset_sha "${sums}" "${name}-${version}-linux-amd64.tar.gz")"

  mkdir -p Formula
  cat >"Formula/${name}.rb" <<EOF
# Generated by scripts/update.sh from the ${tag} release of tsvsheet/${repo} — do not edit by hand.
class ${class} < Formula
  desc "${desc}"
  homepage "https://tsvsheet.com"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/${name}-${version}-darwin-arm64.tar.gz"
      sha256 "${sha_darwin_arm}"
    end
    on_intel do
      url "${base}/${name}-${version}-darwin-amd64.tar.gz"
      sha256 "${sha_darwin_amd}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${name}-${version}-linux-arm64.tar.gz"
      sha256 "${sha_linux_arm}"
    end
    on_intel do
      url "${base}/${name}-${version}-linux-amd64.tar.gz"
      sha256 "${sha_linux_amd}"
    end
  end

  def install
    bin.install Dir["${name}-*"].first => "${name}"
    bash_completion.install "completions/${name}.bash" => "${name}" if File.exist?("completions/${name}.bash")
    zsh_completion.install "completions/${name}.zsh" => "_${name}" if File.exist?("completions/${name}.zsh")
    fish_completion.install "completions/${name}.fish" if File.exist?("completions/${name}.fish")
    man1.install "man/${name}.1" if File.exist?("man/${name}.1")
  end

  test do
    system "#{bin}/${name}", "--version"
  end
end
EOF
  echo "Formula/${name}.rb ← ${tag}"
}

formula tsv tsvsheet.go Tsv "Spreadsheet for plain text — compute .tsvt grids of values and =formulas"
formula isnow isnow.go Isnow "Match instants against isnow date/time patterns"
formula tq tq.go Tq "Query TSV with a pipeline of relational verbs — the tq query language"
